/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai3sw;

import java.awt.List;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Vector;
import javax.print.DocFlavor;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author THUONG THUONG
 */
public class frmBai3SW extends javax.swing.JFrame {

    /**
     * Creates new form frmBai3SW
     */
    public frmBai3SW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listTrai = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPhai = new javax.swing.JList<>();
        btnSangPhai = new javax.swing.JButton();
        btnAllPhai = new javax.swing.JButton();
        btnSangTrai = new javax.swing.JButton();
        btnAllTrai = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ListView Bai3");

        listTrai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTraiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listTrai);

        jScrollPane2.setViewportView(listPhai);

        btnSangPhai.setText(">");
        btnSangPhai.setMinimumSize(new java.awt.Dimension(30, 30));
        btnSangPhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSangPhaiActionPerformed(evt);
            }
        });

        btnAllPhai.setText(">>");
        btnAllPhai.setMinimumSize(new java.awt.Dimension(30, 30));
        btnAllPhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllPhaiActionPerformed(evt);
            }
        });

        btnSangTrai.setText("<");
        btnSangTrai.setMinimumSize(new java.awt.Dimension(30, 30));
        btnSangTrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSangTraiActionPerformed(evt);
            }
        });

        btnAllTrai.setText("<<");
        btnAllTrai.setMinimumSize(new java.awt.Dimension(30, 30));
        btnAllTrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllTraiActionPerformed(evt);
            }
        });

        btnThem.setText("+");
        btnThem.setMinimumSize(new java.awt.Dimension(30, 30));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel1.setText("Danh sách môn thể thao");

        jLabel2.setText("Môn yêu thích");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAllPhai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAllTrai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSangPhai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSangTrai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnSangPhai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAllPhai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSangTrai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAllTrai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))))
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList <String> arrTrai = new ArrayList<>();
    ArrayList <String> arrPhai = new ArrayList<>();
    private void btnSangPhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSangPhaiActionPerformed
    //Lấy vị trí cần di chuyển
        int i = listTrai.getSelectedIndex();
        ListModel model = listTrai.getModel();
    // lấy ra giá tên môn thể thao ở vị trí click chuột
        String sName = model.getElementAt(i).toString();
    //Xóa hết trong list Trái
        arrTrai.clear();
    
        for (int j = 0; j < model.getSize(); j++)
            arrTrai.add((String) model.getElementAt(j));
        arrTrai.remove(i);
        
        String[] dataTrai = arrTrai.toArray(new String[arrTrai.size()+1]);
        listTrai.setListData(dataTrai);
        
        arrPhai.add(sName);
        String[] arData = arrPhai.toArray(new String[arrPhai.size()+1]);
        listPhai.setListData(arData);
    }//GEN-LAST:event_btnSangPhaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
    //Hiện hộp
        String sTheThao = JOptionPane.showInputDialog(this, "Nhập môn thể thao");
    //Thêm vào List Trái
    //2.1
        ListModel mTrai = listTrai.getModel();
    //2.2 Chuyển sang dạng List để xử
        ArrayList<String> lstTrai = new ArrayList<>();
        for(int i=0;i < mTrai.getSize();i++)
            lstTrai.add((String) mTrai.getElementAt(i));
    //Thêm data vừa iput
        lstTrai.add(sTheThao);
    //2.3 đưa ra hiển thị
    //Chuyển list thành mảng để sử dụng phương thức setListData
        String[] arData = lstTrai.toArray(new String[lstTrai.size()+1]);
        listTrai.setListData(arData);
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void listTraiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTraiMouseClicked
        
    }//GEN-LAST:event_listTraiMouseClicked

    private void btnAllPhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllPhaiActionPerformed
        ListModel modelTrai = listTrai.getModel();
        //ListModel modelPhai = listPhai.getModel();
        arrTrai.clear();
        for (int j = 0; j < modelTrai.getSize(); j++)
            arrPhai.add((String) modelTrai.getElementAt(j));
        String[] dataTrai = arrTrai.toArray(new String[arrTrai.size()+1]);
        listTrai.setListData(dataTrai);
        String[] dataPhai = arrPhai.toArray(new String[arrPhai.size()+1]);
        listPhai.setListData(dataPhai);
    }//GEN-LAST:event_btnAllPhaiActionPerformed

    private void btnSangTraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSangTraiActionPerformed
        //Lấy vị trí cần di chuyển
        int i = listPhai.getSelectedIndex();
        ListModel model = listPhai.getModel();
    // lấy ra giá tên môn thể thao ở vị trí click chuột
        String sName = model.getElementAt(i).toString();
    //Xóa hết trong list Trái
        arrPhai.clear();
    
        for (int j = 0; j < model.getSize(); j++)
            arrPhai.add((String) model.getElementAt(j));
        arrPhai.remove(i);
        
        String[] dataTrai = arrPhai.toArray(new String[arrPhai.size()+1]);
        listPhai.setListData(dataTrai);
        
        arrTrai.add(sName);
        String[] arData = arrTrai.toArray(new String[arrTrai.size()+1]);
        listTrai.setListData(arData);
    }//GEN-LAST:event_btnSangTraiActionPerformed

    private void btnAllTraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllTraiActionPerformed
        ListModel modelPhai = listPhai.getModel();
        //ListModel modelPhai = listPhai.getModel();
        arrPhai.clear();
        for (int j = 0; j < modelPhai.getSize(); j++)
            arrTrai.add((String) modelPhai.getElementAt(j));
        String[] dataPhai = arrPhai.toArray(new String[arrPhai.size()+1]);
        listPhai.setListData(dataPhai);
        String[] dataTrai = arrTrai.toArray(new String[arrTrai.size()+1]);
        listTrai.setListData(dataTrai);
    }//GEN-LAST:event_btnAllTraiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBai3SW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBai3SW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBai3SW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBai3SW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBai3SW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllPhai;
    private javax.swing.JButton btnAllTrai;
    private javax.swing.JButton btnSangPhai;
    private javax.swing.JButton btnSangTrai;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listPhai;
    private javax.swing.JList<String> listTrai;
    // End of variables declaration//GEN-END:variables
}
